<?php
# This file was automatically generated by the MediaWiki 1.26.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "@SITENAME@";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/wiki";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "@SERVERNAME@";


## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "/wiki/logos/e-neutrons-logo-blue-small.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "@ADMINMAIL@";
$wgPasswordSender = "@ADMINMAIL@";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "postgres";
$wgDBserver = "localhost";
$wgDBname = "@DBNAME@";
$wgDBuser = "@DBUSER@";
$wgDBpassword = "@DBPASS@";

# Postgres specific settings
$wgDBport           = "5432";
$wgDBmwschema       = "mediawiki";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "80ab5a4900e5248c01eb06d3e6afdeff15127a72b3b565bf3c8d73ace6f41e71";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "2dd677556d8f6717";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-sa/3.0/";
$wgRightsText = "Creative Commons Attribution-ShareAlike";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'CologneBlue' );
wfLoadSkin( 'Modern' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Vector' );


# Enabled Extensions. Most extensions are enabled by including the base extension file here
# but check specific extension documentation for more details
# The following extensions were automatically enabled:
wfLoadExtension( 'PdfHandler' );


# End of automatically generated settings.
# Add more configuration options below.

# LDAP
require_once 'extensions/LdapAuthentication/LdapAuthentication.php';
require_once 'includes/AuthPlugin.php';
$wgAuth = new LdapAuthenticationPlugin();
$wgDebugLogFile = '/srv/mcweb/mediawiki-logfile.log';
$wgDebugLogGroups['ldap'] = '/srv/mcweb/mediawiki-logfile.log';
//$wgShowExceptionDetails = true; //for debugging MediaWiki
$wgLDAPDebug = 3;
$wgLDAPDomainNames = array("@LDAP_FULLDOM_UNDERSCORE@");
$wgLDAPSearchAttributes = array( "@LDAP_FULLDOM_UNDERSCORE@" => "uid" );
$wgLDAPServerNames = array("@LDAP_FULLDOM_UNDERSCORE@" => "localhost");
$wgLDAPUseLocal = true;
$wgLDAPEncryptionType = array("@LDAP_FULLDOM_UNDERSCORE@" => "clear");
$wgLDAPPort = array("@LDAP_FULLDOM_UNDERSCORE@" => 389);
$wgLDAPBaseDNs = array("@LDAP_FULLDOM_UNDERSCORE@" => "@LDAP_DN@");
$wgLDAPGroupBaseDNs = array("@LDAP_FULLDOM_UNDERSCORE@" => "@LDAP_GROUP_OU@");

# PDF generation via the Collection extension
require_once "$IP/extensions/Collection/Collection.php";

# Cross referencing
require_once "$IP/extensions/CrossReference/CrossReference.php";

# Citing with TeX refs
require_once( "$IP/extensions/Cite/Cite.php" );

# Math rendering
require_once "$IP/extensions/Math/Math.php";
# Set MathML as default rendering option;
$wgDefaultUserOptions['math'] = 'mathml';
$wgMathFullRestbaseURL= 'https://api.formulasearchengine.com/';
require_once( "$IP/extensions/MathJax/MathJax.php" );
$wgMathJaxJS = array("/mathjax/MathJax.js?config=default" => "$IP/extensions/MathJax/mwMathJaxConfig.js");

# use parserfunctions extension (used by hide/show template)
require_once( "$IP/extensions/ParserFunctions/ParserFunctions.php" );

# To rename users in a good way without breaking links
require_once("$IP/extensions/Renameuser/Renameuser.php");

require_once("$IP/extensions/PdfExport/PdfExport.php");

# PrinceXML - Works, without formulae
#$wgPdfExportPrincePath = '/usr/bin/prince'; // Path to the PrinceXML binary
#$wgPdfExportPrincePhpInterface = $IP . '/extensions/PdfExport/prince/prince.php'; // Path to the prince.php file from the prince website.

# mwlib - Generates an empty pdf
#$wgPdfExportMwLibPath = '/usr/local/bin/mw-render'; // Path to the mw-render binary

# DomPDF - Does not work
#$wgPdfExportDomPdfConfigFile = $IP . '/extensions/PdfExport/dompdf/dompdf_config.inc.php'; // Path to the DomPdf config file

# XFA - Works, without formulae
$wgPdfExportHtmlDocPath = '/usr/bin/htmldoc';

#require_once( "$IP/extensions/owa/mw_plugin.php" );
#$wgGroupPermissions['sysop']['owa_view'] = true;
#$wgGroupPermissions['user']['owa_view'] = false;

#require_once ("$IP/extensions/OpenWebAnalyticsTracker/OpenWebAnalyticsTracker.php");
#$wgOwaSiteId = 'ece344035c0d8f7a19d23f1696235310';

# Make an extra namespace for exercises
$wgExtraNamespaces[100] = "Problem";
$wgExtraNamespaces[101] = "Problem_talk";
$wgExtraNamespaces[102] = "Simulation_project_SANS-2";
$wgExtraNamespaces[103] = "Simulation_project_SANS-2_talk";
$wgExtraNamespaces[104] = "Simulation_project_tripleaxis";
$wgExtraNamespaces[105] = "Simulation_project_tripleaxis_talk";
$wgExtraNamespaces[106] = "Simulation_project_powder";
$wgExtraNamespaces[107] = "Simulation_project_powder_talk";

define("NS_PROBLEM", 100); 
define("NS_PROBLEM_TALK", 101);
define("NS_SIM_SANS", 102);
define("NS_SIM_SANS_TALK", 103);
define("NS_SIM_TRIP", 104);
define("NS_SIM_TRIP_TALK", 105);
define("NS_SIM_POW", 106);
define("NS_SIM_POW_TALK", 107);

# Group access 
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['read'] = false;
$wgGroupPermissions['*']['createtalk'] = false;
$wgGroupPermissions['*']['createpage'] = false;
$wgGroupPermissions['*']['writeapi'] = false;

#require_once "$IP/extensions/Lockdown/Lockdown.php";

# From https://www.mediawiki.org/wiki/Manual_talk:User_rights:
# An attempt to lock down editing and only allow 'talk' editing for
# the normal 'users'
$wgGroupPermissions['*']['edit-main'] = false;
$wgGroupPermissions['*']['edit-talk'] = true;
$wgGroupPermissions['sysop']['edit-main'] = true;
$wgGroupPermissions['sysop']['edit-talk'] = true;
$wgGroupPermissions['user']['edit-main'] = false;
$wgGroupPermissions['user']['edittalk'] = true;
$wgGroupPermissions['user']['create-talk'] = true;
$wgGroupPermissions['user']['edit-talk'] = true;
$wgGroupPermissions['user']['createtalk'] = true;
$wgNamespaceProtection[NS_MAIN] = array( 'edit-main' );
$wgNamespaceProtection[NS_USER] = array( 'edit-main' );
$wgNamespaceProtection[NS_MEDIAWIKI] = array( 'editmain' );
# The following line is commented out as we never found the proper NS_ label for the site...
# $wgNamespaceProtection[NS_NMI3_Virtual_Neutrons_for_Teaching] = array( 'edit-main' );
$wgNamespaceProtection[NS_HELP] = array( 'edit-main' );

$wgNamespaceProtection[NS_PROBLEM] = array( 'edit-main' );
$wgNamespaceProtection[NS_PROBLEM_TALK] = array( 'edit-talk' );
$wgNamespaceProtection[NS_SIM_SANS] = array( 'edit-main' );
$wgNamespaceProtection[NS_SIM_SANS_TALK] = array( 'edit-talk' );
$wgNamespaceProtection[NS_SIM_TRIP] = array( 'edit-main' );
$wgNamespaceProtection[NS_SIM_TRIP_TALK] = array( 'edit-talk' );
$wgNamespaceProtection[NS_SIM_POW] = array( 'edit-main' );
$wgNamespaceProtection[NS_SIM_POW_TALK] = array( 'edit-talk' );

# lots of permissions to allow for administrators to do stuff
$wgGroupPermissions['sysop']['edit-main'] = true;
$wgGroupPermissions['sysop']['edit-talk'] = true;
$wgGroupPermissions['sysop']['read'] = true;
$wgGroupPermissions['sysop']['createpage'] = true;
$wgGroupPermissions['sysop']['edit'] = true;
$wgGroupPermissions['sysop']['move'] = true;
$wgGroupPermissions['sysop']['minoredit'] = true;
$wgGroupPermissions['sysop']['move-subpages'] = true;
$wgGroupPermissions['sysop']['move-rootuserpages'] = true;
$wgGroupPermissions['sysop']['reupload-shared'] = true;
$wgGroupPermissions['sysop']['reupload'] = true;
$wgGroupPermissions['sysop']['purge'] = true;
$wgGroupPermissions['sysop']['upload'] = true;
$wgGroupPermissions['sysop']['owa_view'] = true;
$wgGroupPermissions['sysop']['writeapi'] = true;

# don't allow for normal users to do much
$wgGroupPermissions['user']['createpage'] = false;
$wgGroupPermissions['user']['createtalk'] = true;
$wgGroupPermissions['user']['create-talk'] = true;
$wgGroupPermissions['user']['edit-talk'] = true;
$wgGroupPermissions['user']['edit'] = true; # <- General EDIT ability needed to allow edit-talk. Denided edit-main protects the real pages...
$wgGroupPermissions['user']['move'] = false;
$wgGroupPermissions['user']['movefile'] = false;
$wgGroupPermissions['user']['minoredit'] = false;
$wgGroupPermissions['user']['move-subpages'] = false;
$wgGroupPermissions['user']['move-rootuserpages'] = false;
$wgGroupPermissions['user']['reupload-shared'] = false;
$wgGroupPermissions['user']['reupload'] = false;
$wgGroupPermissions['user']['purge'] = false;
$wgGroupPermissions['user']['upload'] = false;
$wgGroupPermissions['user']['owa_view'] = false;
$wgGroupPermissions['user']['writeapi'] = false;
$wgGroupPermissions['user']['read'] = true;

# But allow all to read these pages:
$wgWhitelistRead =  array ( "Main Page", "Problem:Fourier_transform", "e-neutrons_wiki:About");

# Control the footer of the page
$wgFooterIcons = array(
        "copyright" => array(
                "copyright" => array(), // placeholder for the built in copyright icon
        ),
        "poweredby" => array(
     #           "mediawiki" => array(
     #                   "src" => null, // Defaults to "$wgStylePath/common/images/poweredby_mediawiki_88x31.png"
     #                   "url" => "http://www.mediawiki.org/",
     #                   "alt" => "Powered by MediaWiki",
     #           )
        ),
);

# KU sponsor logo
$wgFooterIcons['poweredby']['sponsorbuttons3'] = array(
        "src" => "/wiki/logos/buttons3.png", 
        "url" => "/wiki/index.php?title=e-neutrons_wiki:About",
        "alt" => "Sponsors",
        "height" => "31",
        "width" => "99",
);
# NMI3 F7 sponsor logo
$wgFooterIcons['poweredby']['sponsorbuttons1'] = array(
        "src" => "/wiki/logos/buttons1.png", 
        "url" => "/wiki/index.php?title=e-neutrons_wiki:About",
        "alt" => "Sponsors",
        "height" => "31",
        "width" => "135",
);
# ?MIC sponsor logo
$wgFooterIcons['poweredby']['sponsorbuttons2'] = array(
        "src" => "/wiki/logos/buttons2.png", 
        "url" => "/wiki/index.php?title=e-neutrons_wiki:About",
        "alt" => "Sponsors",
        "height" => "31",
        "width" => "319",
);


require_once "$IP/extensions/UserMerge/UserMerge.php";
// By default nobody can use this function, enable for bureaucrat?
$wgGroupPermissions['bureaucrat']['usermerge'] = true;

require_once "$IP/extensions/Piwik/Piwik.php";
$wgPiwikURL = "@PIWIK_URL@";
$wgPiwikIDSite = 1;
$wgPiwikUsernameCustomVariable = array(1, 'User');
