sudo: required
language: python

jobs:
  include:
    - name: "Linux Ubuntu 18.04 (Bionic Beaver)"
      os: linux
      dist: bionic
      python: 3.8
      services: mysql
      env: DJANGO_VERSION=2.2.6 DB=mysql
      
before_script:
  - mysql -e 'create database test;' -u root

install:
  - pip install --upgrade pip
  - pip install Django==$DJANGO_VERSION

before_script:
  - mysql --version
  - python --version
  - python -m pip --version
  - python -m pytest --version
  - python -m django --version
  - echo $TRAVIS_OS_NAME
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_TAG
  - echo $HOME
  
script:
  - cd $TRAVIS_BUILD_DIR/mcsimrunner
  - python tests/tests.py   # unittest
  #- pytest tests/          # pytest
  - python manage.py test   # django
