<?php
# This file was automatically generated by the MediaWiki 1.19.20+dfsg-0+deb7u3
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename      = "NMI3 Virtual Neutrons for Teaching";
$wgMetaNamespace = "NMI3_Virtual_Neutrons_for_Teaching";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "";
$wgArticlePath      = "/index.php?title=$1";
$wgUsePathInfo      = true;
$wgScriptExtension  = ".php";

## The protocol and server name to use in fully-qualified URLs
$wgServer           = "https://vntwiki.mcstas.org";

## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "$wgStylePath/vnt/images/nmi3_logo.png";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "apache@vntwiki.mcstas.org:443";
$wgPasswordSender   = "apache@vntwiki.mcstas.org:443";

$wgEnotifUserTalk      = false; # UPO
$wgEnotifWatchlist     = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "postgres";
$wgDBserver         = "localhost";
$wgDBname           = "tvntwiki";
## Anonymized for putting on GitHub
$wgDBuser           = "xxxxxxx";
$wgDBpassword       = "xxxxxxx";

# Postgres specific settings
$wgDBport           = "5432";
$wgDBmwschema       = "mediawiki";

## Shared memory settings
$wgMainCacheType    = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads  = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons  = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_DK.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "ddfdb282ec4f5f451be4b49f707215d16490279a36d94531e9b8ee3e89651935";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "805549c8a9a331b7";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";
$wgHiddenPrefs[] = 'skin';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl  = "http://creativecommons.org/licenses/by-sa/3.0/";
$wgRightsText = "Creative Commons Attribution Share Alike";
$wgRightsIcon = "{$wgStylePath}/common/images/cc-by-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# debian-specific include:
if (is_file("/etc/mediawiki-extensions/extensions.php")) {
	include("/etc/mediawiki-extensions/extensions.php");
}

# Query string length limit for ResourceLoader. You should only set this if
# your web server has a query string length limit (then set it to that limit),
# or if you have suhosin.get.max_value_length set in php.ini (then set it to
# that value)
$wgResourceLoaderMaxQueryLength = -1;

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;

# Enabled Extensions. Most extensions are enabled by including the base extension file here
# but check specific extension documentation for more details
# The following extensions were automatically enabled:
require_once( "$IP/extensions/Cite/Cite.php" );
require_once( "$IP/extensions/Math/Math.php" );


# End of automatically generated settings.
# Add more configuration options below.

# use the mathjax extension for math
require_once( "$IP/extensions/MathJax/MathJax.php" );
$wgMathJaxJS = array("/mathjax/MathJax.js?config=default" => "$IP/extensions/MathJax/mwMathJaxConfig.js");

# use crossreference extension (for figures/tables)
require_once( "$IP/extensions/CrossReference/CrossReference.php" );

# use parserfunctions extension (used by hide/show template)
require_once( "$IP/extensions/ParserFunctions/ParserFunctions.php" );

# To rename users in a good way without breaking links
require_once("$IP/extensions/Renameuser/Renameuser.php");

$wgShowExceptionDetails = true;
error_reporting( E_ALL );
ini_set( 'display_errors', 1 );

# Make an extra namespace for exercises
$wgExtraNamespaces[100] = "Problem";
$wgExtraNamespaces[101] = "Simulation_project";
$wgExtraNamespaces[102] = "Simulation_project_SANS-2";
$wgExtraNamespaces[103] = "Simulation_project_powder";
$wgExtraNamespaces[104] = "Simulation_project_tripleaxis";

# Control the footer of the page
$wgFooterIcons = array(
        "copyright" => array(
                "copyright" => array(), // placeholder for the built in copyright icon
        ),
        "poweredby" => array(
     #           "mediawiki" => array(
     #                   "src" => null, // Defaults to "$wgStylePath/common/images/poweredby_mediawiki_88x31.png"
     #                   "url" => "http://www.mediawiki.org/",
     #                   "alt" => "Powered by MediaWiki",
     #           )
        ),
);

# KU sponsor logo
$wgFooterIcons['poweredby']['sponsorbuttons3'] = array(
        "src" => "/logos/buttons3.png", // you may also use a direct path to the source, e.g. "http://example.com/my/custom/path/to/MyCustomLogo.png"
        "url" => "http://vnt.nmi3.org/wiki/index.php/NMI3_Virtual_Neutrons_for_Teaching:About",
        "alt" => "Sponsors",
        "height" => "31",
        "width" => "99",
);
# NMI3 F7 sponsor logo
$wgFooterIcons['poweredby']['sponsorbuttons1'] = array(
        "src" => "/logos/buttons1.png", // you may also use a direct path to the source, e.g. "http://example.com/my/custom/path/to/MyCustomLogo.png"
        "url" => "http://vnt.nmi3.org/wiki/index.php/NMI3_Virtual_Neutrons_for_Teaching:About",
        "alt" => "Sponsors",
        "height" => "31",
        "width" => "135",
);
# ?MIC sponsor logo
$wgFooterIcons['poweredby']['sponsorbuttons2'] = array(
        "src" => "/logos/buttons2.png", // you may also use a direct path to the source, e.g. "http://example.com/my/custom/path/to/MyCustomLogo.png"
        "url" => "http://vnt.nmi3.org/wiki/index.php/NMI3_Virtual_Neutrons_for_Teaching:About",
        "alt" => "Sponsors",
        "height" => "31",
        "width" => "319",
);

# Piwik integration
require_once("$IP/extensions/piwik/Piwik.php");
$wgPiwikURL = "vntwiki.mcstas.org/piwik";
$wgPiwikIDSite = 1;
$wgPiwikUsernameCustomVariable = array(1, 'User');

# use open web analytics extension (for statistics)
require_once( "$IP/extensions/owa/mw_plugin.php" );

# For debugging purposes only!! 
# $wgDebugLogFile = "/tmp/wiki.log";

# Group access 
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['read'] = false;
$wgGroupPermissions['*']['createtalk'] = false;
$wgGroupPermissions['*']['createpage'] = false;
$wgGroupPermissions['*']['writeapi'] = false;

#require_once "$IP/extensions/Lockdown/Lockdown.php";

# From https://www.mediawiki.org/wiki/Manual_talk:User_rights:
# An attempt to lock down editing and only allow 'talk' editing for
# the normal 'users'
$wgGroupPermissions['*']['edit-main'] = false;
$wgGroupPermissions['*']['edit-talk'] = false;
$wgGroupPermissions['sysop']['edit-main'] = true;
$wgGroupPermissions['sysop']['edit-talk'] = true;
$wgGroupPermissions['user']['edit-main'] = false;
$wgGroupPermissions['user']['edit-talk'] = true;
$wgNamespaceProtection[NS_MAIN] = array( 'edit-main' );
$wgNamespaceProtection[NS_USER] = array( 'edit-main' );
$wgNamespaceProtection[NS_MEDIAWIKI] = array( 'editmain' );
# The following line is commented out as we never found the proper NS_ label for the site...
# $wgNamespaceProtection[NS_NMI3_Virtual_Neutrons_for_Teaching] = array( 'edit-main' );
$wgNamespaceProtection[NS_HELP] = array( 'edit-main' );
$wgNamespaceProtection[100] = array( 'edit-main' );
$wgNamespaceProtection[101] = array( 'edit-main' );
$wgNamespaceProtection[102] = array( 'edit-main' );
$wgNamespaceProtection[103] = array( 'edit-main' );
$wgNamespaceProtection[104] = array( 'edit-main' );

# lots of permissions to allow for administrators to do stuff
$wgGroupPermissions['sysop']['edit-main'] = true;
$wgGroupPermissions['sysop']['edit-talk'] = true;
$wgGroupPermissions['sysop']['read'] = true;
$wgGroupPermissions['sysop']['createpage'] = true;
$wgGroupPermissions['sysop']['edit'] = true;
$wgGroupPermissions['sysop']['move'] = true;
$wgGroupPermissions['sysop']['minoredit'] = true;
$wgGroupPermissions['sysop']['move-subpages'] = true;
$wgGroupPermissions['sysop']['move-rootuserpages'] = true;
$wgGroupPermissions['sysop']['reupload-shared'] = true;
$wgGroupPermissions['sysop']['reupload'] = true;
$wgGroupPermissions['sysop']['purge'] = true;
$wgGroupPermissions['sysop']['upload'] = true;
$wgGroupPermissions['sysop']['owa_view'] = true;
$wgGroupPermissions['sysop']['writeapi'] = true;

# don't allow for normal users to do much
$wgGroupPermissions['user']['createpage'] = false;
$wgGroupPermissions['user']['createtalk'] = true;
$wgGroupPermissions['user']['edit'] = true; # <- General EDIT ability needed to allow edit-talk. Denided edit-main protects the real pages...
$wgGroupPermissions['user']['move'] = false;
$wgGroupPermissions['user']['movefile'] = false;
$wgGroupPermissions['user']['minoredit'] = false;
$wgGroupPermissions['user']['move-subpages'] = false;
$wgGroupPermissions['user']['move-rootuserpages'] = false;
$wgGroupPermissions['user']['reupload-shared'] = false;
$wgGroupPermissions['user']['reupload'] = false;
$wgGroupPermissions['user']['purge'] = false;
$wgGroupPermissions['user']['upload'] = false;
$wgGroupPermissions['user']['owa_view'] = false;
$wgGroupPermissions['user']['writeapi'] = false;
$wgGroupPermissions['user']['read'] = true;

# But allow all to read these pages:
$wgWhitelistRead =  array ( "Main Page", "Problem:Fourier_transform", "NMI3_Virtual_Neutrons_for_Teaching:About");

