<?xml version="1.0" encoding="UTF-8"?>
<component level='0' library='DirectSensorNodePool' name='DirectSensor' providerUrl='http://www.instantreality.org/' standard='' title='DirectSensor Component'>
  <node level='0' name='DirectSensor'/>
  <node level='0' name='IOSensor'/>
  <node level='0' name='MFBoolSensor'/>
  <node level='0' name='MFColorRGBASensor'/>
  <node level='0' name='MFColorSensor'/>
  <node level='0' name='MFDoubleSensor'/>
  <node level='0' name='MFFloatSensor'/>
  <node level='0' name='MFImageSensor'/>
  <node level='0' name='MFInt32Sensor'/>
  <node level='0' name='MFMatrix3dSensor'/>
  <node level='0' name='MFMatrix3fSensor'/>
  <node level='0' name='MFMatrix4dSensor'/>
  <node level='0' name='MFMatrix4fSensor'/>
  <node level='0' name='MFRotationSensor'/>
  <node level='0' name='MFStringSensor'/>
  <node level='0' name='MFTimeSensor'/>
  <node level='0' name='MFVec2dSensor'/>
  <node level='0' name='MFVec2fSensor'/>
  <node level='0' name='MFVec3dSensor'/>
  <node level='0' name='MFVec3fSensor'/>
  <node level='0' name='MFVec4dSensor'/>
  <node level='0' name='MFVec4fSensor'/>
  <node level='0' name='MultiFieldSensor'/>
  <node level='0' name='SFBoolSensor'/>
  <node level='0' name='SFColorRGBASensor'/>
  <node level='0' name='SFColorSensor'/>
  <node level='0' name='SFDoubleSensor'/>
  <node level='0' name='SFFloatSensor'/>
  <node level='0' name='SFImageSensor'/>
  <node level='0' name='SFInt32Sensor'/>
  <node level='0' name='SFMatrix3dSensor'/>
  <node level='0' name='SFMatrix3fSensor'/>
  <node level='0' name='SFMatrix4dSensor'/>
  <node level='0' name='SFMatrix4fSensor'/>
  <node level='0' name='SFRotationSensor'/>
  <node level='0' name='SFStringSensor'/>
  <node level='0' name='SFTimeSensor'/>
  <node level='0' name='SFVec2dSensor'/>
  <node level='0' name='SFVec2fSensor'/>
  <node level='0' name='SFVec3dSensor'/>
  <node level='0' name='SFVec3fSensor'/>
  <node level='0' name='SFVec4dSensor'/>
  <node level='0' name='SFVec4fSensor'/>
  <node level='0' name='SingleFieldSensor'/><![CDATA[Hold all the low-level sensors which handle the direct input and output to the device subsystem]]>
</component>