<?xml version="1.0" encoding="UTF-8"?>
<component level='0' library='RenderingNodePool' name='Rendering' providerUrl='http://www.instantreality.org/' standard='X3D' title='Rendering Component'>
  <node level='5' name='ClipPlane'/>
  <node level='1' name='Color'/>
  <node level='1' name='ColorRGB'/>
  <node level='4' name='ColorRGBA'/>
  <node level='1' name='Coordinate'/>
  <node level='0' name='Coordinate1D'/>
  <node level='0' name='Coordinate1DD'/>
  <node level='0' name='Coordinate2D'/>
  <node level='0' name='Coordinate2DD'/>
  <node level='1' name='Coordinate3D'/>
  <node level='0' name='Coordinate3DD'/>
  <node level='0' name='CoordinateDouble'/>
  <node level='0' name='CoordinateFloat'/>
  <node level='0' name='DynamicGeometry'/>
  <node level='0' name='ExternPrimitiveSet'/>
  <node level='0' name='FogCoordinate'/>
  <node level='0' name='GeometryProperty'/>
  <node level='0' name='GmlNode'/>
  <node level='0' name='Highlight'/>
  <node level='1' name='IndexedLineSet'/>
  <node level='0' name='IndexedPointSet'/>
  <node level='0' name='IndexedPrimitiveSet'/>
  <node level='0' name='IndexedQuadSet'/>
  <node level='0' name='IndexedQuadStripSet'/>
  <node level='3' name='IndexedTriangleFanSet'/>
  <node level='3' name='IndexedTriangleSet'/>
  <node level='3' name='IndexedTriangleStripSet'/>
  <node level='1' name='LineSet'/>
  <node level='0' name='NonIndexedPrimitiveSet'/>
  <node level='2' name='Normal'/>
  <node level='2' name='Normal3D'/>
  <node level='0' name='ParametricGeometry'/>
  <node level='0' name='ParticleSet'/>
  <node level='0' name='PlanarGeometry'/>
  <node level='1' name='PointSet'/>
  <node level='0' name='PrimitiveSet'/>
  <node level='0' name='PropertySetGeometry'/>
  <node level='0' name='QuadSet'/>
  <node level='0' name='QuadStripSet'/>
  <node level='0' name='SliceSet'/>
  <node level='0' name='SortedPrimitiveSet'/>
  <node level='0' name='SpatialGeometry'/>
  <node level='0' name='SplatSet'/>
  <node level='0' name='StaticGeometry'/>
  <node level='0' name='Terrain'/>
  <node level='0' name='TextureCoordinateBase'/>
  <node level='3' name='TriangleFanSet'/>
  <node level='3' name='TriangleSet'/>
  <node level='3' name='TriangleStripSet'/>
  <node level='0' name='VertexAttribute'/>
  <node level='0' name='ViewDependentGeometry'/>
  <node level='0' name='ViewIndependentGeometry'/><![CDATA[This includes fundamental rendering primitives such as TriangleSets and PointSets, and geometric properties nodes that define how coordinate indices, colors, normals and texture coordinates are specified.]]>
</component>
