<?xml version="1.0" encoding="UTF-8"?>
<component level='0' library='TexturingNodePool' name='Texturing' providerUrl='http://www.instantreality.org/' standard='X3D' title='Texturing Component'>
  <node level='0' name='ComposedTexture'/>
  <node level='0' name='ComposedTileTexture2D'/>
  <node level='0' name='DependentTextureGenerator'/>
  <node level='0' name='DynamicTexture'/>
  <node level='0' name='EnvironmentTexture'/>
  <node level='0' name='IBRTexture'/>
  <node level='0' name='ImageSourceTexture'/>
  <node level='1' name='ImageTexture'/>
  <node level='1' name='ImageTexture1D'/>
  <node level='1' name='ImageTexture2D'/>
  <node level='3' name='MovieTexture'/>
  <node level='2' name='MultiTexture'/>
  <node level='2' name='MultiTextureCoordinate'/>
  <node level='2' name='MultiTextureTransform'/>
  <node level='0' name='NoiseTexture'/>
  <node level='0' name='NormalMap2DGenerator'/>
  <node level='0' name='NormalMap3DGenerator'/>
  <node level='0' name='NormalMapGenerator'/>
  <node level='0' name='PaintTexture'/>
  <node level='0' name='ParametricTexture'/>
  <node level='0' name='PolynomialTextureMap'/>
  <node level='1' name='PixelTexture'/>
  <node level='1' name='PixelTexture1D'/>
  <node level='1' name='PixelTexture2D'/>
  <node level='0' name='PlaybackTexture'/>
  <node level='0' name='PlaybackTexture'/>
  <node level='0' name='RenderedTexture'/>
  <node level='0' name='SingleTexture'/>
  <node level='0' name='SingleTextureCoordinate'/>
  <node level='0' name='SingleTextureTransform'/>
  <node level='0' name='SolidTexture'/>
  <node level='0' name='SphericalHarmonicsGenerator'/>
  <node level='0' name='StillTexture'/>
  <node level='0' name='TextTexture'/>
  <node level='1' name='TextureCoordinate'/>
  <node level='1' name='TextureCoordinate1D'/>
  <node level='1' name='TextureCoordinate2D'/>
  <node level='0' name='TextureCoordinateData'/>
  <node level='2' name='TextureCoordinateGenerator'/>
  <node level='2' name='TextureProperties'/>
  <node level='0' name='TextureTransform'/>
  <node level='0' name='TextureTransform1D'/>
  <node level='0' name='TextureTransform2D'/><![CDATA[This part includes how textures are specified and how they are positioned on the subject geometry.]]>
</component>
