#!/bin/sh
# Script to remove a "absolute-URL" prefix from a moodle mbz course backup
#
# Takes two arguments:
# 1) mbz filename (e.g. testlinks_20170823.mbz)
# 2) The URL to remove, e.g. https://elearn1.fysik.dtu.dk/
# 
# Work:
# 0) Sanity checks and user confirmation
# 1) Unpack the archive
# 2) Find url.xml files within the hierachy
# 3) Use sed to strip off the URL
# 4) Assemble a "status" logfile with the found differences
# 5) Assemble a new mbz under a modified filename

# Check that we have an existent filename
if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide an mbz file as argument \#1
    exit 1;
fi
if [ "x$2" = "x" ]; then
    # No arguments
    echo Please provide a modification URL file as argument \#2
    exit 1;
fi

MBZFILE_IN=$1
MBZBASE=`basename $MBZFILE_IN .mbz`
URL=$2
WORKDIR=`pwd`

if [ -f "$MBZFILE_IN" ]; then
    if [ -f "${MBZBASE}.mbz" ]; then
	echo $MBZBASE.mbz is in $WORKDIR, good
	# Sanity checks on the URL
	regex='(https?)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'
	string='http://www.google.com/test/link.php'
	if [[ $URL =~ $regex ]]; then 
	    echo "URL $URL seems valid"
	    # Create directory for the archive(s)
	    mkdir -p $MBZBASE
	    mkdir -p ${MBZBASE}_URLstrip
	    cd $MBZBASE
	    tar xzf $WORKDIR/$MBZBASE.mbz
	    cd $WORKDIR
	    rsync -avz --delete $MBZBASE/ ${MBZBASE}_URLstrip
	    # On OS X basename needs a suffix to .bak, we'll just remove these by the second find
	    find ${MBZBASE}_URLstrip -name url.xml -exec sed -i.bak "s+${URL}++g" \{\} \;
	    find ${MBZBASE}_URLstrip -name url.xml.bak -exec rm \{\} \;
	    echo URL-strip log for removal of $URL on $MBZFILE_in > ${MBZBASE}_url.striplog
	    echo >> ${MBZBASE}_url.striplog
	    diff -r $MBZBASE ${MBZBASE}_URLstrip >> ${MBZBASE}_url.striplog
	    tar cfz ${MBZBASE}_URLstrip.mbz ${MBZBASE}_URLstrip
	else
	    echo "$URL does not look like a proper URL, exiting"
	    exit 1;
	fi
    else
	echo The file $MBZBASE.mbz is not in your current directory \($WORKDIR\), exiting
	exit 1;
    fi
else
    echo $MBZFILE_IN not found, exiting
    exit 1;
fi