#!/bin/sh
 
### BEGIN INIT INFO
# Provides:          uwsgi-mcweb
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Put a short description of the service here
# Description:       Put a long description of the service here
### END INIT INFO
 
VIRTUALENV=/srv/mcweb/mcvenv/
DIR=/srv/mcweb/McWeb/mcsimrunner/
DAEMON=$VIRTUALENV/bin/uwsgi
WRKDAEMON=$DIR/manage.py
DAEMON_NAME=uwsgi_mcweb
DAEMON_NAME_WRK=mcweb-worker

# This next line determines what user the script runs as.
DAEMON_USER=www-data
 
# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/uwsgi-mcweb
PIDFILE_WRK=/var/run/mcweb-worker
. $VIRTUALENV/bin/activate
. /lib/lsb/init-functions
 
do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER -d $DIR --chuid $DAEMON_USER --exec $DAEMON -- uwsgi_mcweb.ini
    start-stop-daemon --start --background --pidfile $PIDFILE_WRK --make-pidfile --user $DAEMON_USER -d $DIR --chuid $DAEMON_USER --exec $WRKDAEMON -- runworker
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    start-stop-daemon --stop --pidfile $PIDFILE_WRK --retry 10
    log_end_msg $?
}
 
case "$1" in
 
    start|stop)
	cd $DIR
        do_${1}
        ;;
 
    restart|reload|force-reload)
        do_stop
        do_start
        ;;
 
    status)
        status_of_proc -p $PIDFILE "$DAEMON_NAME" "$DAEMON" status_of_proc -p $PIDFILE "$DAEMON_NAME_WRK" "$WRKDAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;
 
esac
exit 0
